name = "insight-hunter"
main = "worker/index.ts"
compatibility_date = "2025-08-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist/client"
binding = "ASSETS"   # must match c.env.ASSETS in index.ts

routes = [
  { pattern = "insight.hunterturner.com", custom_domain = true },
  { pattern = "insight.hunterturner.com/*", custom_domain = true }
]

# --- Optional: Queues (producer) ---
# [[queues.producers]]
# binding = "JOBS"
# queue = "insight-hunter-jobs"

# --- Optional: Durable Objects ---
# [[durable_objects.bindings]]
# name = "SESSION"
# class_name = "SessionDurableObject"

[vars]
TEMPLATE_VERSION = "v1" 
name = "insight-hunter-onboarding"
main = "src/worker.ts"
compatibility_date = "2024-11-21"
APP_ENV = "production"
SESSION_TTL_SECONDS = "604800"

[[d1_databases]]
binding = "DB"
database_name = "insight_hunter_db"
database_id = "3678f73e-c2cb-48fb-9cb4-91e6141024f4"

[[kv_namespaces]]
binding = "KV"
id = "5d547bc308d1445d960d19636c589923"

[[r2_buckets]]
binding = "ASSETS"     # env.ASSETS
bucket_name = "ih-templates"

[vars]
TEMPLATE_VERSION = "v1"  # bump to bust cache

